FROM FROM_IMAGE
MAINTAINER Nate Coraor <nate@bx.psu.edu>
ENV DEBIAN_FRONTEND noninteractive
VOLUME ["/host"]
COPY buildpy.sh /build/buildpy.sh
RUN yum install -y PKGS && \
    cd /build && \
    bash buildpy.sh && \
    cd / && \
    rm -rf /build && \
    yum clean all
