FROM FROM_IMAGE
MAINTAINER Nate Coraor <nate@bx.psu.edu>
ENV DEBIAN_FRONTEND noninteractive
ENV LDFLAGS -L/usr/lib/x86_64-linux-gnu
VOLUME ["/host"]
RUN RUN_CMD && \
    mkdir /build && \
    cd /build && \
    curl -O https://www.python.org/ftp/python/2.6.9/Python-2.6.9.tgz && \
    curl -O https://www.python.org/ftp/python/2.7.10/Python-2.7.10.tgz && \
    tar zxf Python-2.6.9.tgz && \
    tar zxf Python-2.7.10.tgz && \
    cd /build/Python-2.6.9 && \
    ./configure --prefix=/python/2.6-ucs2 --enable-unicode=ucs2 && \
    make install && \
    make distclean && \
    ./configure --prefix=/python/2.6-ucs4 --enable-unicode=ucs4 && \
    make install && \
    cd /build/Python-2.7.10 && \
    ./configure --prefix=/python/2.7-ucs2 --enable-unicode=ucs2 && \
    make install && \
    make distclean && \
    ./configure --prefix=/python/2.7-ucs4 --enable-unicode=ucs4 && \
    make install && \
    cd /build && \
    curl -O https://pypi.python.org/packages/source/s/setuptools/setuptools-18.0.1.tar.gz && \
    tar zxf setuptools-18.0.1.tar.gz && \
    cd setuptools-18.0.1 && \
    python setup.py install && \
    rm -rf build && \
    /python/2.6-ucs2/bin/python setup.py install && \
    rm -rf build && \
    /python/2.6-ucs4/bin/python setup.py install && \
    rm -rf build && \
    /python/2.7-ucs2/bin/python setup.py install && \
    rm -rf build && \
    /python/2.7-ucs4/bin/python setup.py install && \
    cd .. && \
    curl -O https://bitbucket.org/natefoo/wheel/get/WHEEL_VERSION.tar.gz && \
    tar zxf WHEEL_VERSION.tar.gz && \
    cd natefoo-wheel-WHEEL_VERSION && \
    python setup.py install && \
    rm -rf build && \
    /python/2.6-ucs2/bin/python setup.py install && \
    rm -rf build && \
    /python/2.6-ucs4/bin/python setup.py install && \
    rm -rf build && \
    /python/2.7-ucs2/bin/python setup.py install && \
    rm -rf build && \
    /python/2.7-ucs4/bin/python setup.py install && \
    cd .. && \
    rm -rf /build
