FROM FROM_IMAGE
MAINTAINER Nate Coraor <nate@bx.psu.edu>
ENV DEBIAN_FRONTEND noninteractive
VOLUME ["/host"]
COPY buildpy.sh /build/buildpy.sh
RUN linux32 yum install -y PKGS && \
    cd /build && \
    linux32 bash buildpy.sh && \
    cd / && \
    rm -rf /build && \
    linux32 yum clean all
