FROM FROM_IMAGE
MAINTAINER Nate Coraor <nate@bx.psu.edu>
ENV DEBIAN_FRONTEND noninteractive
VOLUME ["/host"]
COPY buildpy.sh /build/buildpy.sh
RUN zypper --non-interactive --gpg-auto-import-keys ref && \
    zypper --non-interactive in PKGS && \
    cd /build && \
    bash buildpy.sh && \
    cd / && \
    rm -rf /build && \
    zypper clean
