FROM BASE_NAME_AND_TAG

MAINTAINER Nate Coraor <nate@bx.psu.edu>

ENV DEBIAN_FRONTEND noninteractive

VOLUME ["/host"]

RUN sed -i 's#deb http://httpredir.debian.org/debian squeeze main#deb http://archive.debian.org/debian squeeze main#g' /etc/apt/sources.list && \
    apt-get -qq update && \
    apt-get install --no-install-recommends -y wget build-essential ADDITIONAL_BUILD_PACKAGES

ENTRYPOINT ["/bin/bash", "/host/build.sh"]
